name: qiyomat_va_oxirat
description: Bismillah.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^3.0.1
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  lottie: ^2.2.0
  anim_search_bar: ^2.0.3
  ff_navigation_bar_plus: ^0.1.5
  shared_preferences: ^2.0.18
  page_route_animator: ^1.0.3
  audioplayers: ^0.20.1
  animated_native_splash: ^1.0.0
  url_launcher: ^6.1.11
  share_plus: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0




animated_native_splash:

  # This package generates native code to customize Flutter's splash

  # jsonFile is the only required parameter.This the file use to setup the animation object.
  jsonFile: assets/lottie/audiobook.json
flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/
    - assets/tres/
    - assets/audios/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
